import type { Database, Station, StoreItem, User } from "./types";
import { COIN_CONFIG } from "./config";

export const STATIONS: Station[] = [
  {
    id: "st-vr",
    name: "VR Zone",
    slug: "vr-zone",
    tag: "Station",
    highlight: "₹400",
    description: "Immersive VR arenas with multiplayer battles and racing sims.",
    pricePerHour: 400,
    icon: "headphones",
    accent: "green",
    image: "/images/stations/vr.png",
  },
  {
    id: "st-racing",
    name: "Racing Simulator",
    slug: "racing-sim",
    tag: "Featured",
    highlight: "₹350",
    description: "Full-motion racing rigs with force feedback and 4K screens.",
    pricePerHour: 350,
    icon: "gauge",
    accent: "yellow",
    image: "/images/stations/racing.png",
  },
  {
    id: "st-ps5",
    name: "PS5 Lounge",
    slug: "ps5-lounge",
    tag: "Popular",
    highlight: "₹250",
    description: "Private booths with DualSense controllers and latest titles.",
    pricePerHour: 250,
    icon: "gamepad-2",
    accent: "red",
    image: "/images/stations/ps5.png",
  },
  {
    id: "st-console",
    name: "Console Bay",
    slug: "console-bay",
    tag: "Station",
    highlight: "₹200",
    description: "Xbox & Switch stations — perfect for parties and co-op.",
    pricePerHour: 200,
    icon: "monitor",
    accent: "orange",
    image: "/images/stations/console.png",
  },
  {
    id: "st-pc",
    name: "PC Arena",
    slug: "pc-arena",
    tag: "Esports",
    highlight: "₹300",
    description: "High-refresh competitive PCs for FPS and MOBA sessions.",
    pricePerHour: 300,
    icon: "cpu",
    accent: "blue",
    image: "/images/stations/pc.png",
  },
  {
    id: "st-party",
    name: "Party Room",
    slug: "party-room",
    tag: "Group",
    highlight: "₹800",
    description: "Private room for up to 8 players with snack service.",
    pricePerHour: 800,
    icon: "users",
    accent: "green",
    image: "/images/stations/party.png",
  },
];

export const STORE_ITEMS: StoreItem[] = [
  {
    id: "item-1hr",
    name: "1 Free Hour Voucher",
    description: "Redeem for one hour at any standard station.",
    coinCost: 150,
    category: "hours",
    accent: "yellow",
    stock: 99,
    image: "/images/store/1hr.png",
  },
  {
    id: "item-2hr",
    name: "2 Free Hours Bundle",
    description: "Double session voucher — stackable with bookings.",
    coinCost: 280,
    category: "hours",
    accent: "green",
    stock: 50,
    image: "/images/store/2hr.png",
  },
  {
    id: "item-tee",
    name: "AimBotz Tee",
    description: "Limited neon print tee — sizes S–XXL.",
    coinCost: 400,
    category: "merch",
    accent: "orange",
    stock: 20,
    image: "/images/store/tee.png",
  },
  {
    id: "item-snack",
    name: "Snack Combo",
    description: "Popcorn + soft drink at the counter.",
    coinCost: 80,
    category: "snacks",
    accent: "red",
    stock: 100,
    image: "/images/store/snack.png",
  },
  {
    id: "item-hood",
    name: "Neon Hoodie",
    description: "Premium black hoodie with embroidered logo.",
    coinCost: 700,
    category: "merch",
    accent: "blue",
    stock: 12,
    image: "/images/store/hood.png",
  },
  {
    id: "item-vip",
    name: "VIP Day Pass",
    description: "Unlimited access to all stations for one day.",
    coinCost: 1200,
    category: "vouchers",
    accent: "yellow",
    stock: 5,
    image: "/images/store/vip.png",
  },
];

export const SEED_USERS: User[] = [
  {
    id: "user-demo",
    name: "Sam Player",
    email: "sam@demo.local",
    coins: 320,
    totalHours: 12.5,
    role: "user",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user-alex",
    name: "Alex Rider",
    email: "alex@demo.local",
    coins: 890,
    totalHours: 28,
    role: "user",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user-mia",
    name: "Mia Chen",
    email: "mia@demo.local",
    coins: 640,
    totalHours: 19,
    role: "user",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user-jay",
    name: "Jay Patel",
    email: "jay@demo.local",
    coins: 410,
    totalHours: 14,
    role: "user",
    createdAt: new Date().toISOString(),
  },
  {
    id: "admin-1",
    name: "Zone Admin",
    email: "admin@aimbotz.local",
    coins: 0,
    totalHours: 0,
    role: "admin",
    createdAt: new Date().toISOString(),
  },
];

export function createSeedDatabase(): Database {
  return {
    users: SEED_USERS,
    bookings: [],
    coinLedger: [
      {
        id: "cl-1",
        userId: "user-demo",
        amount: 200,
        reason: "Welcome bonus",
        createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
      },
      {
        id: "cl-2",
        userId: "user-demo",
        amount: 100,
        reason: "Session completed — PS5 Lounge (2h)",
        bookingId: undefined,
        createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
      {
        id: "cl-3",
        userId: "user-demo",
        amount: 20,
        reason: "Session completed — Console Bay (1h)",
        createdAt: new Date(Date.now() - 86400000).toISOString(),
      },
    ],
    sessions: [],
    storeItems: STORE_ITEMS,
    stations: STATIONS,
    nextResetAt: COIN_CONFIG.nextResetAt,
  };
}
